import Link from "next/link";

const days = [
  { day: 1, website: "FieldNote", category: "Agriculture", websiteDescription: "Crop watchlist and field-readiness companion.", websiteStatus: "Built", href: "/days/day-1" },
  { day: 2, website: "StudySprint", category: "Education", websiteDescription: "Focused revision dashboard for study sessions.", websiteStatus: "Built", href: "/days/day-2" },
  { day: 3, website: "RegexLab", category: "Developer Tool", websiteDescription: "Regex workbench for patterns and replacements.", websiteStatus: "Built", href: "/days/day-3" },
  { day: 4, website: "TimeBox", category: "Productivity", websiteDescription: "25-minute focus timer for one finished task.", websiteStatus: "Built", href: "/days/day-4" },
  { day: 5, website: "PantryPilot", category: "Utility", websiteDescription: "Household inventory and restocking tracker.", websiteStatus: "Built", href: "/days/day-5" },
  { day: 6, website: "SignalSprint", category: "Game", websiteDescription: "Memory game for short focus breaks.", websiteStatus: "Built", href: "/days/day-6" },
  { day: 7, website: "CampusPulse", category: "Dashboard", websiteDescription: "Student momentum dashboard for tasks, study blocks, and progress.", websiteStatus: "Built", href: "/days/day-7" },
  { day: 8, website: "MuseBoard", category: "Creative Experience", websiteDescription: "Moodboard generator with palettes, prompts, and saved directions.", websiteStatus: "Built", href: "/days/day-8" },
  { day: 9, website: "HabitGarden", category: "Wellness", websiteDescription: "Gentle habit tracker for small actions and daily momentum.", websiteStatus: "Built", href: "/days/day-9" },
  { day: 10, website: "BillBloom", category: "Finance", websiteDescription: "Recurring bill planner for a clearer monthly money map.", websiteStatus: "Built", href: "/days/day-10" },
  { day: 11, website: "ResumeForge", category: "Portfolio", websiteDescription: "Job-ready profile builder with a checklist and strength score.", websiteStatus: "Built", href: "/days/day-11" },
  { day: 12, website: "DecisionDeck", category: "Decision Tool", websiteDescription: "Turn a fuzzy choice into a fast, explainable recommendation.", websiteStatus: "Built", href: "/days/day-12" },
  { day: 13, website: "LaunchBoard", category: "Product Tool", websiteDescription: "Score product ideas by impact, reach, and effort before building.", websiteStatus: "Live", href: "/days/day-13" },
];

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f7f5ff;color:#17131f;padding:24px 16px 72px;font-family:Inter,system-ui,sans-serif}.shell{max-width:1080px;margin:auto}.back{display:inline-block;color:#777080;text-decoration:none;font-size:13px;margin-bottom:46px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#8066a8}.hero{display:flex;justify-content:space-between;gap:28px;align-items:end}.hero h1{font-size:clamp(44px,8vw,78px);line-height:.94;letter-spacing:-4px;margin:12px 0 20px}.hero h1 em{font-style:normal;color:#9333ea}.intro{max-width:650px;color:#716b79;line-height:1.7;font-size:15px}.counter{min-width:150px;padding:18px;border:1px solid #ded5ec;background:#fff;border-radius:20px;text-align:center}.counter b{display:block;font-size:30px;letter-spacing:-2px;color:#7c3aed}.counter span{font-size:10px;font-weight:800;letter-spacing:.12em;color:#817889}.timeline{display:grid;gap:18px;margin-top:50px}.day{background:#fff;border:1px solid #e2dced;border-radius:26px;padding:22px;box-shadow:0 14px 35px rgba(76,29,149,.06)}.day-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.day-number{font-size:30px;font-weight:950;letter-spacing:-2px;color:#7c3aed}.day-date{font-size:10px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#91899a}.build-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.build{border:1px solid #e8e2ef;border-radius:20px;padding:19px;background:#fbfaff}.build.website{background:linear-gradient(145deg,#fff,#f8f3ff)}.build.app{background:linear-gradient(145deg,#fff,#f4f7ff)}.build-label{display:flex;justify-content:space-between;gap:12px;align-items:center}.build-label span:first-child{font-size:10px;font-weight:900;letter-spacing:.12em;color:#84798f}.status{font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;border-radius:999px;padding:6px 8px;background:#eee7ff;color:#6d28d9}.build h2{font-size:25px;letter-spacing:-1px;margin:13px 0 6px}.build p{margin:0;color:#77707f;font-size:13px;line-height:1.55}.build-meta{display:flex;justify-content:space-between;gap:10px;margin-top:17px;font-size:10px;color:#92899b;font-weight:800}.open{display:inline-flex;margin-top:15px;color:#7c3aed;text-decoration:none;font-size:11px;font-weight:900}.app-note{color:#77707f;font-size:13px;line-height:1.55;margin-top:14px}.footer-note{margin-top:24px;padding:19px 21px;border-radius:20px;background:#191522;color:#f8f4ff;display:flex;justify-content:space-between;gap:15px;font-size:13px}.footer-note span{color:#b9b1c6}@media(max-width:700px){.hero{display:block}.counter{margin-top:20px;max-width:180px}.build-grid{grid-template-columns:1fr}.hero h1{letter-spacing:-3px}.day{padding:17px}.day-head{align-items:start}.build h2{font-size:22px}.footer-note{flex-direction:column;gap:5px}}`;

export const metadata = { title: "Daily Builds · Gokul" };

export default function DaysPage() {
  return <main className="page"><style>{styles}</style><div className="shell"><Link className="back" href="/">← Home</Link><header><div className="eyebrow">DAILY BUILDS · WEBSITE + APP</div><div className="hero"><div><h1>Build every day.<br/><em>Ship twice.</em></h1><p className="intro">A transparent build journal for Gokul AI. Website builds are listed here, while an app download appears only when a real daily app has been created and released.</p></div><div className="counter"><b>{days.length}</b><span>DAYS TRACKED</span></div></div></header><section className="timeline" aria-label="Daily website and app builds">{days.map((item)=><article className="day" key={item.day}><div className="day-head"><span className="day-number">DAY {String(item.day).padStart(2,"0")}</span><span className="day-date">Website + App</span></div><div className="build-grid"><div className="build website"><div className="build-label"><span>🌐 WEBSITE BUILD</span><span className="status">{item.websiteStatus}</span></div><h2>{item.website}</h2><p>{item.websiteDescription}</p><div className="build-meta"><span>{item.category}</span><span>NEXT.JS</span></div><Link className="open" href={item.href}>Open daily build ↗</Link></div><div className="build app"><div className="build-label"><span>📱 APP BUILD</span><span className="status">NOT RELEASED</span></div><h2>No daily app yet</h2><p>This slot stays empty until an actual app is created for this day. No generic Gokul AI APK is shown here.</p><div className="build-meta"><span>ANDROID</span><span>WHEN CREATED</span></div><p className="app-note">When a real daily app is shipped, this card will show its own name and exact release download.</p></div></div></article>)}</section><div className="footer-note"><strong>Focused build history.</strong><span>Only real daily apps will receive a download link.</span></div></div></main>;
}
