"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

const presets = {
  "Study desk": {focus:45, breakTime:10, note:"One clear block. Phone away. Finish with one visible outcome."},
  "Deep work": {focus:60, breakTime:15, note:"Protect the first block from notifications and context switching."},
  "Quick reset": {focus:25, breakTime:5, note:"Small enough to start now. End by writing the next action."},
};

export default function FocusForge(){
  const [mode,setMode]=useState<keyof typeof presets>("Study desk");
  const [blocks,setBlocks]=useState(3);
  const [task,setTask]=useState("Finish the most important task");
  const plan=useMemo(()=>presets[mode],[mode]);
  const focusMinutes=plan.focus*blocks;
  const breakMinutes=plan.breakTime*Math.max(0,blocks-1);
  const total=focusMinutes+breakMinutes;
  return <main style={{minHeight:"100vh",padding:"24px 16px 64px",background:"#f7f5ef",color:"#20241f",fontFamily:"Inter,system-ui,sans-serif"}}>
    <style>{`*{box-sizing:border-box}.shell{max-width:1000px;margin:auto}.back{display:inline-block;color:#77766e;text-decoration:none;font-size:13px;margin-bottom:34px}.eyebrow{font-size:11px;letter-spacing:.16em;font-weight:900;color:#6f6251}.hero{max-width:760px}.hero h1{font-size:clamp(48px,9vw,92px);line-height:.9;letter-spacing:-5px;margin:12px 0 20px}.hero h1 em{font-style:normal;color:#b65d35}.intro{max-width:680px;color:#6d6c64;line-height:1.75;font-size:15px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:34px}.panel{background:#fffefa;border:1px solid #e4dfd3;border-radius:28px;padding:22px;box-shadow:0 18px 38px rgba(63,52,35,.06)}.panel h2{margin:0 0 16px;font-size:20px;letter-spacing:-.7px}.label{display:block;font-size:12px;font-weight:800;color:#77756c;margin:13px 0 8px}.select,.text{width:100%;border:1px solid #ddd7c9;border-radius:14px;padding:13px 14px;background:#fbfaf5;font:inherit;color:inherit}.range{width:100%;accent-color:#b65d35}.value{font-size:30px;font-weight:900;letter-spacing:-1px}.metric{display:flex;justify-content:space-between;align-items:center;padding:13px 0;border-bottom:1px solid #ece7dc}.metric:last-child{border-bottom:0}.metric b{font-size:13px}.metric span{font-weight:900}.timeline{display:grid;gap:8px;margin-top:18px}.step{display:flex;gap:10px;align-items:center;padding:11px 12px;border-radius:14px;background:#f3eee4}.num{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#262b25;color:#fff;font-size:11px;font-weight:900}.cta{margin-top:18px;padding:18px;border-radius:20px;background:#252b25;color:#f8f5ed}.cta strong{display:block;font-size:34px;letter-spacing:-1px;color:#f2b08e}.cta p{margin:6px 0 0;color:#d5d0c5;font-size:13px;line-height:1.55}.chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.chip{font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;padding:7px 9px;border-radius:999px;background:#f0e5d7;color:#8b4e30}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero h1{letter-spacing:-3px}.panel{padding:18px}}`}</style>
    <div className="shell"><Link href="/days" className="back">← Daily Builds</Link><div className="hero"><div className="eyebrow">DAY 24 · PRODUCTIVITY</div><h1>Forge a <em>focus</em> block.</h1><p className="intro">FocusForge turns a vague to-do into a small, time-boxed session with a clear finish line. No account, no notifications, no productivity theatre.</p></div>
    <div className="grid"><section className="panel"><h2>Build the session</h2><label className="label">What are you working on?</label><input className="text" value={task} onChange={e=>setTask(e.target.value)} maxLength={80}/><label className="label">Session style</label><select className="select" value={mode} onChange={e=>setMode(e.target.value as keyof typeof presets)}>{Object.keys(presets).map(k=><option key={k}>{k}</option>)}</select><label className="label">Focus blocks · {blocks}</label><input className="range" type="range" min="1" max="6" value={blocks} onChange={e=>setBlocks(Number(e.target.value))}/><div className="value">{focusMinutes} min focused</div><div className="chips"><span className="chip">Local-only</span><span className="chip">No login</span><span className="chip">Mobile ready</span></div></section>
    <aside className="panel"><h2>Your session map</h2><div className="metric"><b>Focus time</b><span>{focusMinutes} min</span></div><div className="metric"><b>Break time</b><span>{breakMinutes} min</span></div><div className="metric"><b>Total window</b><span>{total} min</span></div><div className="timeline">{Array.from({length:blocks}).map((_,i)=><div className="step" key={i}><span className="num">{i+1}</span><span><b>{plan.focus} min</b> · {i===blocks-1?"finish + capture the result":"focus on the task"}</span></div>)}</div><div className="cta"><div className="eyebrow" style={{color:"#d9a58c"}}>FINISH LINE</div><strong>{task || "Your task"}</strong><p>{plan.note}</p></div></aside></div></div></main>;
}
