"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f4f5f1;color:#1f2427;padding:22px 16px 56px;font-family:Inter,system-ui,sans-serif}.shell{max-width:980px;margin:auto}.back{display:inline-block;color:#727a76;text-decoration:none;font-size:13px;margin-bottom:42px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#7d8780}h1{font-size:clamp(44px,8vw,78px);line-height:.95;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#3d7c70}.intro{max-width:640px;color:#6f7771;line-height:1.7;font-size:15px}.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:18px;margin-top:36px}.panel{background:#fffdf8;border:1px solid #dfe3dc;border-radius:26px;padding:22px;box-shadow:0 16px 32px rgba(40,50,45,.05)}.panel h2{font-size:20px;letter-spacing:-.7px;margin:0 0 16px}.fields{display:grid;gap:12px}.label{font-size:12px;font-weight:800;color:#6f7771}.input,.textarea{width:100%;border:1px solid #d8ddd5;border-radius:14px;background:#f9faf7;padding:13px 14px;font:inherit;color:#1f2427}.textarea{min-height:96px;resize:vertical}.range{width:100%}.score{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:16px;padding:16px;border-radius:18px;background:#edf3ee}.score strong{font-size:38px;letter-spacing:-2px;color:#3d7c70}.muted{color:#788078;font-size:13px;line-height:1.55}.criteria{display:grid;gap:10px}.criteria div{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #ecefe9}.criteria div:last-child{border-bottom:0}.criteria b{font-size:13px}.pill{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#3d7c70;background:#e8f0ea;border-radius:999px;padding:7px 9px}.button{margin-top:16px;border:0;border-radius:14px;padding:13px 15px;background:#273239;color:#fff;font-weight:800;cursor:pointer}.result{margin-top:14px;padding:14px;border-radius:16px;background:#273239;color:#eef3ef;font-size:14px;line-height:1.55}.result b{color:#bfe7d8}@media(max-width:760px){.grid{grid-template-columns:1fr}h1{letter-spacing:-3px}.panel{padding:18px}}`;

export default function DecisionDeckPage(){
  const [title,setTitle]=useState("Should I join the weekend hackathon?");
  const [impact,setImpact]=useState(7);
  const [effort,setEffort]=useState(5);
  const [confidence,setConfidence]=useState(6);
  const [notes,setNotes]=useState("Meet new teammates, build a stronger demo, and learn from feedback.");
  const score = useMemo(()=>Math.round((impact*2 + confidence*1.5 - effort)*10)/10,[impact,effort,confidence]);
  const verdict = score >= 16 ? "Go for it" : score >= 10 ? "Test it first" : "Park it for now";
  return <main className="page"><style>{styles}</style><div className="shell"><Link className="back" href="/days">← Daily Builds</Link><div className="eyebrow">DAY 12 · DECISION TOOL</div><h1>Think clearly.<br/><em>Choose deliberately.</em></h1><p className="intro">DecisionDeck turns a fuzzy choice into a fast, explainable recommendation using impact, effort, and confidence.</p><div className="grid"><section className="panel"><h2>Build your decision</h2><div className="fields"><div><div className="label">Decision title</div><input className="input" value={title} onChange={e=>setTitle(e.target.value)} /></div><div><div className="label">What would improve if you choose it?</div><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)} /></div><div><div className="label">Impact · {impact}/10</div><input className="range" type="range" min="1" max="10" value={impact} onChange={e=>setImpact(Number(e.target.value))}/></div><div><div className="label">Effort · {effort}/10</div><input className="range" type="range" min="1" max="10" value={effort} onChange={e=>setEffort(Number(e.target.value))}/></div><div><div className="label">Confidence · {confidence}/10</div><input className="range" type="range" min="1" max="10" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/></div></div><button className="button" onClick={()=>navigator.clipboard?.writeText(`${title}\nVerdict: ${verdict}\nScore: ${score}/25\n${notes}`)}>Copy decision note</button></section><aside className="panel"><h2>Decision snapshot</h2><div className="score"><div><div className="muted">Weighted score</div><strong>{score}</strong><div className="muted">out of 25</div></div><span className="pill">{verdict}</span></div><div className="criteria"><div><b>Impact</b><span>{impact}/10</span></div><div><b>Effort</b><span>{effort}/10</span></div><div><b>Confidence</b><span>{confidence}/10</span></div></div><div className="result"><b>{verdict}.</b> {score >= 16 ? "The upside is strong enough to justify the work." : score >= 10 ? "Run a small experiment before making a full commitment." : "Keep the idea visible, but protect your time for a stronger option."}</div><p className="muted" style={{marginTop:16}}>A useful decision is not always the exciting one—it is the one you can explain and act on.</p></aside></div></div></main>
}
