"use client";

import { useMemo, useState } from "react";

const initialSections = [
  { id: "summary", label: "Summary", done: true },
  { id: "skills", label: "Skills", done: true },
  { id: "projects", label: "Projects", done: false },
  { id: "experience", label: "Experience", done: false },
];

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f7f5ff;color:#24213a;padding:20px 16px 56px;font-family:Inter,system-ui,sans-serif}.shell{max-width:960px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:30px}.back{color:#77748d;text-decoration:none;font-size:13px}.badge{font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#6d58c8;background:#ece7ff;border-radius:999px;padding:8px 10px}.hero{display:grid;gap:14px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#8075ac}.hero h1{font-size:clamp(42px,8vw,78px);line-height:.94;letter-spacing:-4px;margin:0;max-width:800px}.hero h1 em{font-style:normal;color:#7457d6}.hero p{max-width:640px;color:#78758f;line-height:1.7;margin:0;font-size:15px}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px;margin-top:30px}.panel{background:#fff;border:1px solid #e4def8;border-radius:24px;padding:20px;box-shadow:0 14px 35px rgba(86,68,140,.06)}.panel h2{margin:0 0 16px;font-size:19px}.check-list{display:grid;gap:10px}.check{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px;border:1px solid #eeeafd;border-radius:16px}.check strong{display:block;font-size:14px}.check span{font-size:12px;color:#8b86a2}.toggle{border:0;border-radius:999px;padding:8px 11px;font-weight:800;cursor:pointer;background:#f0edf9;color:#6f63a0}.toggle.done{background:#dcd2ff;color:#5e43c2}.meter{height:12px;background:#efecf8;border-radius:999px;overflow:hidden;margin:8px 0 16px}.meter i{display:block;height:100%;background:#7a5bd6;border-radius:inherit}.score{display:flex;align-items:end;justify-content:space-between;gap:12px}.score strong{font-size:44px;letter-spacing:-3px}.score span{color:#7c788e;font-size:13px}.tip{margin-top:18px;padding:14px 16px;border-radius:16px;background:#f1edff;color:#665b91;font-size:13px;line-height:1.5}.cta{margin-top:18px;width:100%;border:0;border-radius:14px;padding:13px 16px;background:#2f245e;color:#fff;font-weight:900;cursor:pointer}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero h1{letter-spacing:-3px}}`;

export default function ResumeForgePage(){
  const [sections,setSections] = useState(initialSections);
  const [copied,setCopied] = useState(false);
  const complete = useMemo(()=>sections.filter((section)=>section.done).length,[sections]);
  const percent = Math.round((complete/sections.length)*100);
  function toggle(id:string){setSections((items)=>items.map((item)=>item.id===id?{...item,done:!item.done}:item));}
  function copyHeadline(){navigator.clipboard?.writeText("Agricultural Engineering student building practical AI products");setCopied(true);setTimeout(()=>setCopied(false),1200);}
  return <main className="page"><style>{styles}</style><div className="shell"><div className="top"><a className="back" href="/days">← Daily Builds</a><span className="badge">Day 11 · Portfolio</span></div><header className="hero"><div className="eyebrow">RESUMEFORGE · JOB-READY PROFILE BUILDER</div><h1>Make your profile<br/><em>easy to remember.</em></h1><p>A focused portfolio utility for students and early builders: complete the right sections, sharpen your headline, and leave with a cleaner story.</p></header><section className="grid"><div className="panel"><h2>Profile checklist</h2><div className="check-list">{sections.map((section)=><div className="check" key={section.id}><div><strong>{section.label}</strong><span>{section.done?"Ready to show":"Needs one clear proof point"}</span></div><button className={`toggle ${section.done?"done":""}`} onClick={()=>toggle(section.id)}>{section.done?"Done":"Mark ready"}</button></div>)}</div><div className="tip">Keep every section concrete: one action, one result, one reason it mattered.</div></div><div className="panel"><h2>Profile strength</h2><div className="score"><strong>{percent}%</strong><span>{complete} of {sections.length} sections ready</span></div><div className="meter"><i style={{width:`${percent}%`}} /></div><button className="cta" onClick={copyHeadline}>{copied?"Headline copied":"Copy sample headline"}</button><div className="tip">Sample: “Agricultural Engineering student building practical AI products.”</div></div></section></div></main>;
}
