"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f3f6f5;color:#1d2a2a;padding:24px 16px 64px;font-family:Inter,system-ui,sans-serif}.shell{max-width:1040px;margin:auto}.back{display:inline-block;color:#6f7d7b;text-decoration:none;font-size:13px;margin-bottom:40px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#60837d}.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:18px;align-items:stretch}.panel{background:#fffdf9;border:1px solid #dfe8e4;border-radius:28px;padding:24px;box-shadow:0 18px 34px rgba(33,55,50,.06)}h1{font-size:clamp(46px,8vw,82px);line-height:.94;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#2c8a74}.intro{max-width:650px;color:#71807c;line-height:1.75;font-size:15px}.fields{display:grid;gap:14px;margin-top:24px}.label{font-size:12px;font-weight:800;color:#687774}.input,.select{width:100%;border:1px solid #d8e4df;border-radius:14px;background:#fbfdfc;padding:13px 14px;font:inherit;color:#1d2a2a}.range{width:100%}.button{margin-top:18px;border:0;border-radius:14px;padding:13px 16px;background:#1f3a36;color:#fff;font-weight:800;cursor:pointer}.preview{display:grid;gap:16px}.metric{display:flex;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid #edf1ef}.metric:last-child{border-bottom:0}.metric strong{font-size:28px;letter-spacing:-1px;color:#2c8a74}.badge{display:inline-flex;align-items:center;gap:8px;padding:8px 10px;border-radius:999px;background:#e7f4ee;color:#2c8a74;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.note{margin-top:18px;padding:15px 16px;border-radius:16px;background:#1f3a36;color:#eef8f3;line-height:1.55;font-size:14px}.small{font-size:13px;color:#71807c;line-height:1.55}@media(max-width:760px){.hero{grid-template-columns:1fr}.panel{padding:18px}h1{letter-spacing:-3px}}`;

export default function SafeStepsPage(){
  const [people,setPeople]=useState(2);
  const [minutes,setMinutes]=useState(20);
  const [mode,setMode]=useState("Walking");
  const [checkIn,setCheckIn]=useState(false);
  const eta = useMemo(()=>Math.max(5, Math.round(minutes + people*2)),[minutes,people]);
  const status = checkIn ? "Check-in ready" : "Set a safety check-in";
  return <main className="page"><style>{styles}</style><div className="shell"><Link className="back" href="/days">← Daily Builds</Link><div className="eyebrow">DAY 18 · PERSONAL UTILITY</div><h1>Move with a plan.<br/><em>Arrive with confidence.</em></h1><p className="intro">SafeSteps turns a short outing into a lightweight safety plan with a shared check-in, travel mode, and realistic arrival window.</p><div className="hero"><section className="panel"><h2 style={{margin:0,fontSize:22}}>Build a quick plan</h2><div className="fields"><div><div className="label">Travel mode</div><select className="select" value={mode} onChange={e=>setMode(e.target.value)}><option>Walking</option><option>Bus</option><option>Bike</option><option>Car</option></select></div><div><div className="label">People in the plan · {people}</div><input className="range" type="range" min="1" max="6" value={people} onChange={e=>setPeople(Number(e.target.value))}/></div><div><div className="label">Base travel time · {minutes} min</div><input className="range" type="range" min="5" max="60" step="5" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></div><label style={{display:'flex',gap:10,alignItems:'center',fontSize:14,color:'#42514d'}}><input type="checkbox" checked={checkIn} onChange={e=>setCheckIn(e.target.checked)} /> Add a trusted check-in</label></div><button className="button" onClick={()=>navigator.clipboard?.writeText(`SafeSteps plan\nMode: ${mode}\nPeople: ${people}\nArrival window: ${eta} min\n${status}`)}>Copy plan</button></section><aside className="panel"><div className="preview"><div className="badge">{status}</div><div className="metric"><span>Travel mode</span><strong>{mode}</strong></div><div className="metric"><span>Arrival window</span><strong>{eta} min</strong></div><div className="metric"><span>Plan size</span><strong>{people}</strong></div><div className="note"><b>Keep it simple.</b><br/>Share the plan, keep your phone charged, and send a quick update when you arrive.</div><p className="small">SafeSteps is a planning aid, not an emergency service.</p></div></aside></div></div></main>
}
