"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

const samples=[
  {name:"Email",regex:"^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",text:"gokul@example.com"},
  {name:"Phone",regex:"^\\+?[0-9 ()-]{8,}$",text:"+91 98765 43210"},
  {name:"URL",regex:"^https?:\\/\\/[^\\s]+$",text:"https://example.com/docs"},
];

export default function RegexBench(){
 const [pattern,setPattern]=useState(samples[0].regex); const [text,setText]=useState(samples[0].text); const [flags,setFlags]=useState("i");
 const result=useMemo(()=>{try{const r=new RegExp(pattern,flags); const m=r.exec(text); return {ok:true,match:!!m,detail:m?`Matched “${m[0]}”`:"No match"};}catch(e){return {ok:false,match:false,detail:e instanceof Error?e.message:"Invalid pattern"};}},[pattern,text,flags]);
 return <main style={{minHeight:"100vh",padding:"24px 16px 70px",background:"#101315",color:"#f2f5f3",fontFamily:"Inter,system-ui,sans-serif"}}><style>{`*{box-sizing:border-box}.shell{max-width:1050px;margin:auto}.back{display:inline-block;color:#8e9a96;text-decoration:none;font-size:13px;margin-bottom:34px}.eyebrow{font-size:10px;letter-spacing:.18em;font-weight:900;color:#7fd5aa}.hero{max-width:800px}.hero h1{font-size:clamp(48px,9vw,92px);line-height:.9;letter-spacing:-5px;margin:12px 0 20px}.hero h1 em{font-style:normal;color:#7fd5aa}.intro{max-width:690px;color:#a8b1ad;line-height:1.75;font-size:15px}.grid{display:grid;grid-template-columns:1.05fr .95fr;gap:18px;margin-top:34px}.panel{background:#171b1d;border:1px solid #29312f;border-radius:26px;padding:22px;box-shadow:0 20px 50px rgba(0,0,0,.22)}.panel h2{margin:0 0 18px;font-size:19px}.label{display:block;font-size:11px;font-weight:800;color:#8e9a96;margin:14px 0 8px}.input,.area{width:100%;border:1px solid #303936;border-radius:14px;padding:13px 14px;background:#0e1112;color:#edf3ef;font:inherit;outline:none}.area{min-height:150px;resize:vertical}.input:focus,.area:focus{border-color:#7fd5aa}.row{display:grid;grid-template-columns:1fr 90px;gap:10px}.samples{display:flex;flex-wrap:wrap;gap:8px;margin-top:15px}.sample{border:1px solid #33403a;background:#111716;color:#b9c6c0;padding:8px 10px;border-radius:999px;font-size:11px;font-weight:800;cursor:pointer}.sample:hover{border-color:#7fd5aa;color:#e5fff1}.status{padding:18px;border-radius:18px;margin-top:18px;background:#101716;border:1px solid #293b33}.status.good{border-color:#35634e}.status.bad{border-color:#6b3c3c}.status b{font-size:27px;display:block;letter-spacing:-1px}.status.good b{color:#7fd5aa}.status.bad b{color:#ff9696}.code{margin-top:16px;padding:16px;border-radius:16px;background:#0c0f10;color:#c9d4cf;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.7;overflow:auto}.tips{display:grid;gap:10px;margin-top:16px}.tip{padding:12px 14px;border-radius:14px;background:#1d2422;color:#aebbb5;font-size:12px;line-height:1.55}.tip strong{color:#edf3ef}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero h1{letter-spacing:-3px}.panel{padding:18px}.row{grid-template-columns:1fr 78px}}`}</style>
 <div className="shell"><Link href="/days" className="back">← Daily Builds</Link><div className="hero"><div className="eyebrow">DAY 25 · DEVELOPER TOOL</div><h1>Test patterns <em>before</em> they ship.</h1><p className="intro">RegexBench is a tiny browser-only regex tester for checking a pattern against real sample text, spotting syntax errors, and keeping the feedback immediate.</p></div>
 <div className="grid"><section className="panel"><h2>Pattern bench</h2><label className="label">Regular expression</label><input className="input" value={pattern} onChange={e=>setPattern(e.target.value)} spellCheck={false}/><div className="row"><div><label className="label">Test text</label><textarea className="area" value={text} onChange={e=>setText(e.target.value)}/></div><div><label className="label">Flags</label><input className="input" value={flags} onChange={e=>setFlags(e.target.value.replace(/[^dgimsuvy]/g,""))} maxLength={8}/></div></div><div className="samples">{samples.map(s=><button className="sample" key={s.name} onClick={()=>{setPattern(s.regex);setText(s.text);setFlags("i")}}>{s.name}</button>)}</div></section>
 <aside className="panel"><h2>Live result</h2><div className={`status ${result.ok&&result.match?"good":"bad"}`}><div className="eyebrow">{result.ok?"MATCH CHECK":"PATTERN ERROR"}</div><b>{result.ok?(result.match?"Match found":"No match"):"Invalid regex"}</b><span style={{color:"#9da9a4",fontSize:12}}>{result.detail}</span></div><div className="code">/{pattern || ""}/{flags}<br/><br/>input → {text || "empty"}</div><div className="tips"><div className="tip"><strong>Keep it small.</strong> Test the exact input shape you expect before adding more conditions.</div><div className="tip"><strong>Browser only.</strong> Nothing is sent to a server or stored by this tool.</div></div></aside></div></div></main>;
}
