"use client";

import { useMemo, useState } from "react";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f4f6f3;color:#1e2925;padding:24px 16px 56px;font-family:Inter,system-ui,sans-serif}.shell{max-width:980px;margin:auto}.back{display:inline-block;color:#6b756f;text-decoration:none;font-size:13px;margin-bottom:42px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#718078}h1{font-size:clamp(44px,8vw,82px);line-height:.94;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#2f7a64}.intro{max-width:680px;color:#6f7a73;line-height:1.75;font-size:15px}.grid{display:grid;grid-template-columns:1.08fr .92fr;gap:18px;margin-top:36px}.panel{background:#fffefa;border:1px solid #dbe3dc;border-radius:26px;padding:22px;box-shadow:0 16px 32px rgba(40,50,45,.05)}.panel h2{font-size:20px;letter-spacing:-.7px;margin:0 0 16px}.fields{display:grid;gap:12px}.label{font-size:12px;font-weight:800;color:#718078}.input{width:100%;border:1px solid #d7e0d8;border-radius:14px;background:#fbfcfa;padding:13px 14px;font:inherit;color:#1e2925}.checks{display:grid;gap:10px;margin-top:4px}.check{display:flex;align-items:center;gap:10px;padding:12px;border-radius:14px;background:#f0f5f1}.check input{width:18px;height:18px}.progress{height:10px;background:#e9efea;border-radius:999px;overflow:hidden;margin:12px 0}.bar{height:100%;background:#2f7a64;border-radius:999px;transition:width .2s}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.stat{padding:14px;border-radius:16px;background:#eff5f0}.stat strong{display:block;font-size:26px;letter-spacing:-1px;color:#2f7a64}.muted{color:#738078;font-size:13px;line-height:1.55}.button{margin-top:16px;border:0;border-radius:14px;padding:13px 15px;background:#27352f;color:#fff;font-weight:800;cursor:pointer}.route{display:grid;gap:12px}.stop{display:flex;gap:12px;align-items:flex-start;padding:14px;border:1px solid #e1e8e2;border-radius:16px;background:#fbfcfa}.dot{width:12px;height:12px;border-radius:50%;background:#2f7a64;margin-top:4px;flex:0 0 auto}.stop b{display:block;margin-bottom:4px}.tag{display:inline-block;margin-top:7px;font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#2f7a64;background:#e6f0e8;border-radius:999px;padding:6px 8px}@media(max-width:760px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr 1fr}.panel{padding:18px}h1{letter-spacing:-3px}}`;

export default function RouteReadyPage(){
  const [destination,setDestination]=useState("Chennai weekend reset");
  const [checks,setChecks]=useState([true,false,true,false]);
  const done=checks.filter(Boolean).length;
  const percent=Math.round(done/checks.length*100);
  const readiness=useMemo(()=>percent>=75?"Ready to go":percent>=50?"Almost ready":"Needs a few basics",[percent]);
  const toggle=(i:number)=>setChecks(v=>v.map((x,idx)=>idx===i?!x:x));
  return <main className="page"><style>{styles}</style><div className="shell"><a className="back" href="/days">← Daily Builds</a><div className="eyebrow">DAY 14 · TRAVEL UTILITY</div><h1>Pack less.<br/><em>Plan better.</em></h1><p className="intro">RouteReady turns a vague trip into a calm, checkable launch plan with one destination, four essentials, and a simple readiness signal.</p><div className="grid"><section className="panel"><h2>Trip setup</h2><div className="fields"><div><div className="label">Trip name</div><input className="input" value={destination} onChange={e=>setDestination(e.target.value)} /></div><div><div className="label">Essentials</div><div className="checks">{["ID + tickets","Stay confirmed","Weather checked","Emergency contact shared"].map((label,i)=><label className="check" key={label}><input type="checkbox" checked={checks[i]} onChange={()=>toggle(i)}/><span>{label}</span></label>)}</div></div></div><button className="button" onClick={()=>navigator.clipboard?.writeText(`${destination}\nReadiness: ${readiness}\n${checks.map((x,i)=>`${x?'✓':'○'} ${['ID + tickets','Stay confirmed','Weather checked','Emergency contact shared'][i]}`).join('\n')}`)}>Copy trip checklist</button></section><aside className="panel"><h2>Launch snapshot</h2><div className="muted">{destination}</div><div className="progress"><div className="bar" style={{width:`${percent}%`}}/></div><div className="stats"><div className="stat"><strong>{percent}%</strong><span className="muted">ready</span></div><div className="stat"><strong>{done}</strong><span className="muted">done</span></div><div className="stat"><strong>{checks.length-done}</strong><span className="muted">left</span></div></div><p className="tag">{readiness}</p><div className="route"><div className="stop"><span className="dot"/><div><b>Before leaving</b><span className="muted">Finish the essentials above and save the checklist.</span></div></div><div className="stop"><span className="dot"/><div><b>On the move</b><span className="muted">Keep one offline note with address, contact, and return plan.</span></div></div></div></aside></div></div></main>
}
