"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f4f1ff;color:#241f36;padding:24px 16px 64px;font-family:Inter,system-ui,sans-serif}.shell{max-width:1000px;margin:auto}.back{display:inline-block;color:#77718a;text-decoration:none;font-size:13px;margin-bottom:42px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#857ca0}h1{font-size:clamp(44px,8vw,78px);line-height:.94;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#805ad5}.intro{max-width:680px;color:#746d86;line-height:1.7;font-size:15px}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px;margin-top:38px}.panel{background:#fff;border:1px solid #e5def7;border-radius:26px;padding:22px;box-shadow:0 16px 38px rgba(78,58,120,.08)}.panel h2{font-size:20px;letter-spacing:-.7px;margin:0 0 16px}.label{font-size:12px;font-weight:800;color:#746d86;margin-bottom:7px}.textarea{width:100%;min-height:220px;resize:vertical;border:1px solid #ded6ef;border-radius:16px;background:#fbfaff;padding:14px;font:inherit;color:#241f36;line-height:1.6}.row{display:flex;flex-wrap:wrap;gap:10px;margin-top:14px}.select,.button{border:1px solid #ded6ef;border-radius:13px;padding:12px 13px;font:inherit}.select{background:#fbfaff;color:#241f36}.button{border:0;background:#2c2542;color:#fff;font-weight:800;cursor:pointer}.button.secondary{background:#ece6fa;color:#463766}.output{min-height:220px;padding:16px;border-radius:18px;background:#2c2542;color:#f8f4ff;white-space:pre-wrap;line-height:1.65;font-size:14px}.pill{display:inline-block;font-size:11px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;color:#805ad5;background:#f0eaff;border-radius:999px;padding:7px 9px;margin-bottom:14px}.hint{color:#746d86;font-size:13px;line-height:1.55;margin-top:14px}@media(max-width:760px){.grid{grid-template-columns:1fr}h1{letter-spacing:-3px}.panel{padding:18px}}`;

const starter = "Create a concise landing-page headline for a student productivity app. Mention the main outcome, keep it under 10 words, and avoid hype.";

export default function PromptPocketPage(){
  const [prompt,setPrompt]=useState(starter);
  const [tone,setTone]=useState("Clear");
  const [length,setLength]=useState("Short");
  const [copied,setCopied]=useState(false);
  const output = useMemo(()=>`PromptPocket rewrite\n\nTone: ${tone}\nLength: ${length}\n\n${prompt}\n\nChecklist\n• State one clear outcome\n• Remove vague filler words\n• Keep the user and action visible`,[prompt,tone,length]);
  return <main className="page"><style>{styles}</style><div className="shell"><Link className="back" href="/days">← Daily Builds</Link><div className="eyebrow">DAY 13 · AI TOOL</div><h1>Make prompts<br/><em>more useful.</em></h1><p className="intro">PromptPocket is a lightweight prompt workbench for tightening instructions before you paste them into an AI workflow.</p><div className="grid"><section className="panel"><h2>Prompt workbench</h2><div className="label">Draft prompt</div><textarea className="textarea" value={prompt} onChange={e=>setPrompt(e.target.value)} /><div className="row"><select className="select" value={tone} onChange={e=>setTone(e.target.value)}><option>Clear</option><option>Friendly</option><option>Professional</option><option>Bold</option></select><select className="select" value={length} onChange={e=>setLength(e.target.value)}><option>Short</option><option>Medium</option><option>Detailed</option></select><button className="button" onClick={()=>{setCopied(false);}}>Refine prompt</button><button className="button secondary" onClick={()=>{navigator.clipboard?.writeText(output);setCopied(true);}}>Copy</button></div>{copied&&<p className="hint">Copied to clipboard.</p>}</section><aside className="panel"><span className="pill">Preview</span><div className="output">{output}</div><p className="hint">Use it before building with Gemini, ChatGPT, or your own API route. No API key is required for this local refinement view.</p></aside></div></div></main>
}
