"use client";

import { useMemo, useState } from "react";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#eef4f0;color:#20312b;padding:24px 16px 56px;font-family:Inter,system-ui,sans-serif}.shell{max-width:980px;margin:auto}.back{display:inline-block;color:#6a776f;text-decoration:none;font-size:13px;margin-bottom:42px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#648074}h1{font-size:clamp(44px,8vw,82px);line-height:.95;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#2f8b67}.intro{max-width:650px;color:#6b7870;line-height:1.7;font-size:15px}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px;margin-top:36px}.panel{background:#fbfffc;border:1px solid #d6e2da;border-radius:26px;padding:22px;box-shadow:0 16px 32px rgba(40,70,55,.06)}.panel h2{font-size:20px;margin:0 0 16px}.fields{display:grid;gap:12px}.label{font-size:12px;font-weight:800;color:#6b7870}.input,.textarea,.select{width:100%;border:1px solid #d4e0d8;border-radius:14px;background:#f7fbf8;padding:13px 14px;font:inherit;color:#20312b}.textarea{min-height:96px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.button{margin-top:16px;border:0;border-radius:14px;padding:13px 15px;background:#203f34;color:#fff;font-weight:800;cursor:pointer}.cards{display:grid;gap:10px;margin-top:12px}.card{display:flex;justify-content:space-between;gap:12px;padding:14px 0;border-bottom:1px solid #e9f0eb}.card:last-child{border-bottom:0}.card b{font-size:14px}.muted{color:#728078;font-size:13px;line-height:1.55}.pill{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#2f8b67;background:#e6f2ea;border-radius:999px;padding:7px 9px;white-space:nowrap}.summary{margin-top:16px;padding:16px;border-radius:18px;background:#203f34;color:#eff8f2;font-size:14px;line-height:1.6}.summary b{color:#b8f0ce}@media(max-width:760px){.grid{grid-template-columns:1fr}.row{grid-template-columns:1fr}h1{letter-spacing:-3px}.panel{padding:18px}}`;

export default function NeighbourNotePage(){
  const [title,setTitle]=useState("Pick up a parcel from the gate");
  const [area,setArea]=useState("Street 4");
  const [when,setWhen]=useState("Today · before 7 PM");
  const [note,setNote]=useState("Small errand for a neighbour who is away for the evening.");
  const [posted,setPosted]=useState(false);
  const preview = useMemo(()=>({title: title || "Untitled request", area, when, note}),[title,area,when,note]);
  return <main className="page"><style>{styles}</style><div className="shell"><a className="back" href="/days">← Daily Builds</a><div className="eyebrow">DAY 17 · COMMUNITY UTILITY</div><h1>Make small help<br/><em>easy to ask for.</em></h1><p className="intro">NeighbourNote is a tiny local request board for errands, check-ins, and shared support—simple enough to post in under a minute.</p><div className="grid"><section className="panel"><h2>Post a note</h2><div className="fields"><div><div className="label">Request title</div><input className="input" value={title} onChange={e=>setTitle(e.target.value)} /></div><div className="row"><div><div className="label">Area</div><input className="input" value={area} onChange={e=>setArea(e.target.value)} /></div><div><div className="label">Timing</div><select className="select" value={when} onChange={e=>setWhen(e.target.value)}><option>Today · before 7 PM</option><option>Tomorrow morning</option><option>This weekend</option></select></div></div><div><div className="label">A little context</div><textarea className="textarea" value={note} onChange={e=>setNote(e.target.value)} /></div></div><button className="button" onClick={()=>setPosted(true)}>{posted ? "Note posted" : "Post to local board"}</button></section><aside className="panel"><h2>Live preview</h2><div className="card"><div><b>{preview.title}</b><div className="muted">{preview.area} · {preview.when}</div></div><span className="pill">Open</span></div><div className="summary"><b>Why this works:</b> clear request, useful timing, and just enough context for someone nearby to say yes.</div><div className="cards"><div className="card"><div><b>Keep it local</b><div className="muted">Name the street, block, or apartment group.</div></div></div><div className="card"><div><b>Make it easy to answer</b><div className="muted">Short requests get faster replies.</div></div></div></div><p className="muted" style={{marginTop:16}}>No account, API, or personal data storage is required for this prototype.</p></aside></div></div></main>
}
