"use client";

import { useMemo, useState } from "react";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f4f7fb;color:#1e2733;padding:24px 16px 56px;font-family:Inter,system-ui,sans-serif}.shell{max-width:1080px;margin:auto}.back{display:inline-block;color:#657184;text-decoration:none;font-size:13px;margin-bottom:42px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#718097}h1{font-size:clamp(44px,8vw,80px);line-height:.95;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#3e7ad6}.intro{max-width:650px;color:#6d7886;line-height:1.7;font-size:15px}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px;margin-top:36px}.panel{background:#fff;border:1px solid #dce4ee;border-radius:26px;padding:22px;box-shadow:0 16px 34px rgba(31,58,91,.06)}.panel h2{font-size:20px;letter-spacing:-.7px;margin:0 0 16px}.textarea{width:100%;min-height:260px;resize:vertical;border:1px solid #d9e1eb;border-radius:16px;background:#fbfdff;padding:14px;font:inherit;color:#1e2733;line-height:1.55}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{padding:14px;border-radius:18px;background:#edf4ff}.stat b{display:block;font-size:28px;letter-spacing:-1px;color:#2c66b2}.muted{color:#7a8491;font-size:13px;line-height:1.55}.rows{display:grid;gap:10px;margin-top:18px}.row{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #edf1f5}.row:last-child{border-bottom:0}.row b{font-size:13px}.pill{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#2f69bc;background:#eaf2ff;border-radius:999px;padding:7px 9px}.chips{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.chip{padding:8px 10px;border-radius:999px;background:#f0f4f8;color:#516071;font-size:12px;font-weight:800}.button{margin-top:16px;border:0;border-radius:14px;padding:13px 15px;background:#1f3552;color:#fff;font-weight:800;cursor:pointer}@media(max-width:760px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr 1fr}h1{letter-spacing:-3px}.panel{padding:18px}}`;

export default function DataLensPage(){
  const [text,setText] = useState("name,score\nAsha,92\nBala,81\nChitra,88\nDev,74");
  const rows = useMemo(()=>text.trim().split(/\\n+/).filter(Boolean),[text]);
  const columns = useMemo(()=>rows[0]?.split(",").map((x)=>x.trim()).filter(Boolean) ?? [],[rows]);
  const dataRows = Math.max(rows.length-1,0);
  const missing = rows.slice(1).reduce((sum,row)=>sum + row.split(",").filter((v)=>!v.trim()).length,0);
  const numericCells = rows.slice(1).flatMap((row)=>row.split(",")).filter((v)=>v.trim() && !Number.isNaN(Number(v.trim()))).length;
  return <main className="page"><style>{styles}</style><div className="shell"><a className="back" href="/days">← Daily Builds</a><div className="eyebrow">DAY 15 · DEVELOPER TOOL</div><h1>See your data.<br/><em>Before you ship it.</em></h1><p className="intro">DataLens is a tiny browser-only CSV inspector for checking shape, missing values, and numeric density before a spreadsheet turns into a debugging problem.</p><div className="grid"><section className="panel"><h2>Paste CSV</h2><textarea className="textarea" value={text} onChange={(e)=>setText(e.target.value)} aria-label="CSV input" /><button className="button" onClick={()=>navigator.clipboard?.writeText(JSON.stringify({columns,rows:dataRows,missing,numericCells},null,2))}>Copy data summary</button></section><aside className="panel"><h2>Quick scan</h2><div className="stats"><div className="stat"><span className="muted">Columns</span><b>{columns.length}</b></div><div className="stat"><span className="muted">Rows</span><b>{dataRows}</b></div><div className="stat"><span className="muted">Missing</span><b>{missing}</b></div></div><div className="rows"><div className="row"><b>Shape</b><span className="pill">{columns.length} × {dataRows}</span></div><div className="row"><b>Numeric cells</b><span>{numericCells}</span></div><div className="row"><b>Readiness</b><span>{missing === 0 && columns.length > 0 ? "Clean sample" : "Review inputs"}</span></div></div><div className="chips">{columns.map((column)=><span className="chip" key={column}>{column}</span>)}</div><p className="muted" style={{marginTop:16}}>Runs locally in your browser. Nothing is uploaded.</p></aside></div></div></main>
}
