"use client";
import {useMemo,useState} from "react";
import Link from "next/link";

const modes = {
  "Emergency buffer": {weeks: 6, note: "Build a calm cushion before optimizing anything else."},
  "Goal purchase": {weeks: 18, note: "Turn a future purchase into a weekly target you can see."},
  "Debt clear-out": {weeks: 12, note: "Focus extra cash on one balance while keeping essentials visible."},
};

export default function MoneyMap(){
  const [mode,setMode]=useState<keyof typeof modes>("Emergency buffer");
  const [income,setIncome]=useState(30000);
  const [fixed,setFixed]=useState(14000);
  const [weekly,setWeekly]=useState(3000);
  const free=Math.max(0,income-fixed-weekly*4);
  const target=useMemo(()=>Math.round(free*0.35),[free]);
  const months=Math.max(1,Math.ceil((modes[mode].weeks*weekly)/(Math.max(target,1)*4)));
  return <main style={{minHeight:"100vh",padding:"24px 16px 56px",background:"#f4f6f2",color:"#1e2724",fontFamily:"Inter,system-ui,sans-serif"}}>
    <style>{`*{box-sizing:border-box}.shell{max-width:980px;margin:auto}.back{color:#6c766e;text-decoration:none;font-size:13px;display:inline-block;margin-bottom:36px}.eyebrow{font-size:11px;letter-spacing:.16em;font-weight:900;color:#4d7a69}h1{font-size:clamp(46px,8vw,84px);line-height:.94;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#2f8a67}.intro{max-width:650px;color:#6f7972;line-height:1.7;font-size:15px}.grid{display:grid;grid-template-columns:1.02fr .98fr;gap:18px;margin-top:34px}.panel{background:#fcfdfb;border:1px solid #dbe4dd;border-radius:26px;padding:22px;box-shadow:0 16px 32px rgba(41,72,56,.06)}.panel h2{margin:0 0 16px;font-size:20px;letter-spacing:-.8px}.label{display:block;font-size:12px;font-weight:800;color:#6e7771;margin:12px 0 8px}.select,.range{width:100%}.select{border:1px solid #d7e0d8;border-radius:14px;padding:13px 14px;background:#f7faf7;font:inherit}.range{accent-color:#2f8a67}.metric{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid #e7eee8}.metric:last-child{border-bottom:0}.metric b{font-size:13px}.metric span{font-weight:900}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.chip{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;border-radius:999px;padding:7px 9px;background:#e5f1ea;color:#39755b}.hero{margin-top:18px;padding:18px;border-radius:18px;background:#22332d;color:#f3f7f3}.hero strong{display:block;font-size:40px;letter-spacing:-1px;color:#b8f0cf;margin-top:4px}.hero p{margin:6px 0 0;color:#c9d9ce;font-size:13px;line-height:1.5}@media(max-width:760px){.grid{grid-template-columns:1fr}h1{letter-spacing:-3px}.panel{padding:18px}}`}</style>
    <div className="shell"><Link href="/days" className="back">← Daily Builds</Link><div className="eyebrow">DAY 23 · FINANCE UTILITY</div><h1>Give every rupee<br/><em>a direction.</em></h1><p className="intro">MoneyMap turns a monthly snapshot into one clear next move—without pretending that a perfect budget is the same thing as a useful one.</p>
    <div className="grid"><section className="panel"><h2>Shape the plan</h2><label className="label">Main money goal</label><select className="select" value={mode} onChange={e=>setMode(e.target.value as keyof typeof modes)}>{Object.keys(modes).map(k=><option key={k}>{k}</option>)}</select><label className="label">Monthly take-home · ₹{income.toLocaleString("en-IN")}</label><input className="range" type="range" min="12000" max="100000" step="1000" value={income} onChange={e=>setIncome(Number(e.target.value))}/><label className="label">Fixed essentials · ₹{fixed.toLocaleString("en-IN")}</label><input className="range" type="range" min="5000" max={Math.max(5000,income-1000)} step="500" value={fixed} onChange={e=>setFixed(Math.min(Number(e.target.value),Math.max(5000,income-1000)))}/><label className="label">Flexible weekly spend · ₹{weekly.toLocaleString("en-IN")}</label><input className="range" type="range" min="500" max="12000" step="250" value={weekly} onChange={e=>setWeekly(Number(e.target.value))}/><div className="chips"><span className="chip">Local-first</span><span className="chip">No login</span><span className="chip">Private</span></div></section>
    <aside className="panel"><h2>Your next move</h2><div className="metric"><b>Monthly free cash</b><span>₹{free.toLocaleString("en-IN")}</span></div><div className="metric"><b>Suggested target</b><span>₹{target.toLocaleString("en-IN")}</span></div><div className="metric"><b>Estimated runway</b><span>{months} mo</span></div><div className="hero"><div className="eyebrow" style={{color:"#a8d9bc"}}>KEEP IT SIMPLE</div><strong>₹{target.toLocaleString("en-IN")}</strong><p>{modes[mode].note} Start with this amount, then adjust after one real week—not one imaginary month.</p></div><p style={{color:"#758078",fontSize:13,lineHeight:1.6,marginTop:14}}>This is a planning aid, not financial advice. Your real life gets the final vote.</p></aside></div></div></main>;
}
