"use client";

import { useMemo, useState } from "react";

const styles = `*{box-sizing:border-box}.page{min-height:100vh;background:#f4f8f1;color:#1e2a22;padding:24px 16px 56px;font-family:Inter,system-ui,sans-serif}.shell{max-width:1080px;margin:auto}.back{display:inline-block;color:#68766b;text-decoration:none;font-size:13px;margin-bottom:42px}.eyebrow{font-size:11px;font-weight:900;letter-spacing:.16em;color:#718177}h1{font-size:clamp(44px,8vw,80px);line-height:.95;letter-spacing:-4px;margin:12px 0 18px}h1 em{font-style:normal;color:#4b8b55}.intro{max-width:650px;color:#6c7a70;line-height:1.7;font-size:15px}.grid{display:grid;grid-template-columns:1.08fr .92fr;gap:18px;margin-top:36px}.panel{background:#fff;border:1px solid #dce8dc;border-radius:26px;padding:22px;box-shadow:0 16px 34px rgba(44,75,46,.06)}.panel h2{font-size:20px;letter-spacing:-.7px;margin:0 0 16px}.fields{display:grid;gap:12px}.label{font-size:12px;font-weight:800;color:#6e7c71}.input,.select{width:100%;border:1px solid #d9e5d9;border-radius:14px;background:#fbfefb;padding:13px 14px;font:inherit;color:#1e2a22}.range{width:100%}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stat{padding:14px;border-radius:18px;background:#edf6ea}.stat b{display:block;font-size:28px;letter-spacing:-1px;color:#3f7d4b}.muted{color:#78867b;font-size:13px;line-height:1.55}.rows{display:grid;gap:10px;margin-top:18px}.row{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid #edf2eb}.row:last-child{border-bottom:0}.row b{font-size:13px}.pill{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#3f7d4b;background:#e7f3e4;border-radius:999px;padding:7px 9px}.button{margin-top:16px;border:0;border-radius:14px;padding:13px 15px;background:#243a29;color:#fff;font-weight:800;cursor:pointer}.note{margin-top:16px;padding:14px;border-radius:16px;background:#243a29;color:#edf7ed;font-size:14px;line-height:1.55}.note b{color:#b9e7ba}@media(max-width:760px){.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr 1fr}h1{letter-spacing:-3px}.panel{padding:18px}}`;

const crops = { Rice:{water:8,days:120}, Tomato:{water:6,days:90}, Groundnut:{water:4,days:110}, Millet:{water:3,days:85} } as const;

export default function CropCuePage(){
  const [crop,setCrop] = useState<keyof typeof crops>("Rice");
  const [area,setArea] = useState(2);
  const [soil,setSoil] = useState(6);
  const plan = useMemo(()=>{ const base=crops[crop]; const water=Math.max(1,Math.round(base.water*area*(1.2-soil/20))); const harvest=Math.round(base.days+(6-soil)*3); const score=Math.max(0,Math.min(100,Math.round(68 + soil*3 - area*2))); return {water,harvest,score};},[crop,area,soil]);
  return <main className="page"><style>{styles}</style><div className="shell"><a className="back" href="/days">← Daily Builds</a><div className="eyebrow">DAY 16 · AGRICULTURE PLANNER</div><h1>Plan the crop.<br/><em>Protect the season.</em></h1><p className="intro">CropCue is a lightweight field planning companion for estimating water rhythm, harvest window, and readiness from a few practical inputs.</p><div className="grid"><section className="panel"><h2>Field inputs</h2><div className="fields"><div><div className="label">Crop</div><select className="select" value={crop} onChange={e=>setCrop(e.target.value as keyof typeof crops)}>{Object.keys(crops).map(name=><option key={name}>{name}</option>)}</select></div><div><div className="label">Area · {area} acres</div><input className="range" type="range" min="1" max="10" value={area} onChange={e=>setArea(Number(e.target.value))}/></div><div><div className="label">Soil readiness · {soil}/10</div><input className="range" type="range" min="1" max="10" value={soil} onChange={e=>setSoil(Number(e.target.value))}/></div></div><button className="button" onClick={()=>navigator.clipboard?.writeText(`CropCue plan\nCrop: ${crop}\nArea: ${area} acres\nEstimated water rhythm: ${plan.water} units/week\nHarvest window: ${plan.harvest} days\nReadiness: ${plan.score}%`)}>Copy field plan</button></section><aside className="panel"><h2>Season snapshot</h2><div className="stats"><div className="stat"><span className="muted">Water rhythm</span><b>{plan.water}</b></div><div className="stat"><span className="muted">Harvest days</span><b>{plan.harvest}</b></div><div className="stat"><span className="muted">Readiness</span><b>{plan.score}%</b></div></div><div className="rows"><div className="row"><b>Crop</b><span className="pill">{crop}</span></div><div className="row"><b>Field size</b><span>{area} acres</span></div><div className="row"><b>Next action</b><span>{soil < 5 ? "Improve soil" : soil < 8 ? "Monitor moisture" : "Ready to schedule"}</span></div></div><div className="note"><b>Field note:</b> Use this as a planning estimate, then validate with local weather, soil tests, and extension guidance.</div></aside></div></div></main>
}
